export type PropertyCategory = 'general' | 'gameplay' | 'world' | 'players' | 'performance' | 'advanced';
export type PropertyControl = 'boolean' | 'number' | 'text' | 'select';

export interface PropertyOption {
    label: string;
    value: string;
}

export interface PropertyDefinition {
    key: string;
    label: string;
    description: string;
    category: PropertyCategory;
    control: PropertyControl;
    defaultValue: string;
    options?: PropertyOption[];
    min?: number;
    max?: number;
    step?: number;
    placeholder?: string;
    restart?: boolean;
    warning?: string;
}

export interface PropertyPreset {
    id: string;
    name: string;
    description: string;
    accent: string;
    values: Record<string, string>;
}

const yesNo: PropertyOption[] = [
    { label: 'Ativado', value: 'true' },
    { label: 'Desativado', value: 'false' },
];

export const propertyDefinitions: PropertyDefinition[] = [
    {
        key: 'motd',
        label: 'Mensagem do servidor',
        description: 'Texto exibido na lista de servidores do Minecraft.',
        category: 'general',
        control: 'text',
        defaultValue: 'A Minecraft Server',
        placeholder: 'Meu servidor Minecraft',
    },
    {
        key: 'max-players',
        label: 'Máximo de jogadores',
        description: 'Quantidade máxima de jogadores conectados ao mesmo tempo.',
        category: 'general',
        control: 'number',
        defaultValue: '20',
        min: 1,
        max: 10000,
        restart: true,
    },
    {
        key: 'enable-status',
        label: 'Exibir status público',
        description: 'Permite que o servidor apareça como online na lista de servidores.',
        category: 'general',
        control: 'boolean',
        defaultValue: 'true',
        options: yesNo,
    },
    {
        key: 'hide-online-players',
        label: 'Ocultar jogadores online',
        description: 'Não envia a lista de jogadores na resposta de status do servidor.',
        category: 'general',
        control: 'boolean',
        defaultValue: 'false',
        options: yesNo,
    },
    {
        key: 'resource-pack',
        label: 'URL do resource pack',
        description: 'Link HTTPS direto para um pacote de recursos opcional.',
        category: 'general',
        control: 'text',
        defaultValue: '',
        placeholder: 'https://exemplo.com/pack.zip',
    },
    {
        key: 'require-resource-pack',
        label: 'Exigir resource pack',
        description: 'Desconecta jogadores que recusarem o pacote de recursos.',
        category: 'general',
        control: 'boolean',
        defaultValue: 'false',
        options: yesNo,
    },
    {
        key: 'resource-pack-prompt',
        label: 'Mensagem do resource pack',
        description: 'Mensagem JSON exibida antes do download do pacote.',
        category: 'general',
        control: 'text',
        defaultValue: '',
        placeholder: '{"text":"Recomendamos nosso pacote!"}',
    },
    {
        key: 'gamemode',
        label: 'Modo de jogo',
        description: 'Modo padrão aplicado aos novos jogadores.',
        category: 'gameplay',
        control: 'select',
        defaultValue: 'survival',
        options: [
            { label: 'Sobrevivência', value: 'survival' },
            { label: 'Criativo', value: 'creative' },
            { label: 'Aventura', value: 'adventure' },
            { label: 'Espectador', value: 'spectator' },
        ],
    },
    {
        key: 'difficulty',
        label: 'Dificuldade',
        description: 'Controla dano, fome e criaturas hostis.',
        category: 'gameplay',
        control: 'select',
        defaultValue: 'easy',
        options: [
            { label: 'Pacífico', value: 'peaceful' },
            { label: 'Fácil', value: 'easy' },
            { label: 'Normal', value: 'normal' },
            { label: 'Difícil', value: 'hard' },
        ],
    },
    {
        key: 'hardcore',
        label: 'Modo hardcore',
        description: 'Jogadores viram espectadores ao morrer e a dificuldade fica no máximo.',
        category: 'gameplay',
        control: 'boolean',
        defaultValue: 'false',
        options: yesNo,
        warning: 'Ativar hardcore muda permanentemente a experiência do mundo.',
    },
    {
        key: 'pvp',
        label: 'Combate entre jogadores',
        description: 'Permite que jogadores causem dano uns aos outros.',
        category: 'gameplay',
        control: 'boolean',
        defaultValue: 'true',
        options: yesNo,
    },
    {
        key: 'allow-flight',
        label: 'Permitir voo',
        description: 'Evita expulsar jogadores detectados voando.',
        category: 'gameplay',
        control: 'boolean',
        defaultValue: 'false',
        options: yesNo,
    },
    {
        key: 'force-gamemode',
        label: 'Forçar modo padrão',
        description: 'Aplica o modo padrão sempre que um jogador entrar.',
        category: 'gameplay',
        control: 'boolean',
        defaultValue: 'false',
        options: yesNo,
    },
    {
        key: 'spawn-protection',
        label: 'Proteção do spawn',
        description: 'Raio protegido ao redor do spawn. Use 0 para desativar.',
        category: 'gameplay',
        control: 'number',
        defaultValue: '16',
        min: 0,
        max: 10000,
    },
    {
        key: 'allow-nether',
        label: 'Permitir Nether',
        description: 'Habilita viagens e geração da dimensão Nether.',
        category: 'gameplay',
        control: 'boolean',
        defaultValue: 'true',
        options: yesNo,
    },
    {
        key: 'enable-command-block',
        label: 'Command blocks',
        description: 'Permite o uso de blocos de comando.',
        category: 'gameplay',
        control: 'boolean',
        defaultValue: 'false',
        options: yesNo,
    },
    {
        key: 'level-name',
        label: 'Nome do mundo',
        description: 'Pasta do mundo carregada pelo servidor.',
        category: 'world',
        control: 'text',
        defaultValue: 'world',
        placeholder: 'world',
        restart: true,
        warning: 'Alterar o nome carrega ou cria outra pasta de mundo no próximo início.',
    },
    {
        key: 'level-seed',
        label: 'Seed do mundo',
        description: 'Seed usada somente ao gerar um mundo novo.',
        category: 'world',
        control: 'text',
        defaultValue: '',
        placeholder: 'Vazio para uma seed aleatória',
        restart: true,
    },
    {
        key: 'level-type',
        label: 'Tipo do mundo',
        description: 'Gerador utilizado na criação de um mundo novo.',
        category: 'world',
        control: 'select',
        defaultValue: 'minecraft:normal',
        options: [
            { label: 'Normal', value: 'minecraft:normal' },
            { label: 'Plano', value: 'minecraft:flat' },
            { label: 'Biomas grandes', value: 'minecraft:large_biomes' },
            { label: 'Amplificado', value: 'minecraft:amplified' },
            { label: 'Bioma único', value: 'minecraft:single_biome_surface' },
        ],
        restart: true,
    },
    {
        key: 'generate-structures',
        label: 'Gerar estruturas',
        description: 'Gera vilas, templos, fortalezas e outras estruturas.',
        category: 'world',
        control: 'boolean',
        defaultValue: 'true',
        options: yesNo,
    },
    {
        key: 'max-world-size',
        label: 'Tamanho máximo do mundo',
        description: 'Raio máximo da borda do mundo em blocos.',
        category: 'world',
        control: 'number',
        defaultValue: '29999984',
        min: 1,
        max: 29999984,
        restart: true,
    },
    {
        key: 'view-distance',
        label: 'Distância de visão',
        description: 'Quantidade de chunks enviados a cada jogador.',
        category: 'world',
        control: 'number',
        defaultValue: '10',
        min: 3,
        max: 32,
    },
    {
        key: 'simulation-distance',
        label: 'Distância de simulação',
        description: 'Raio de chunks onde entidades e redstone continuam processando.',
        category: 'world',
        control: 'number',
        defaultValue: '10',
        min: 3,
        max: 32,
    },
    {
        key: 'online-mode',
        label: 'Autenticação oficial',
        description: 'Valida contas na Mojang/Microsoft. Recomendado para servidores públicos.',
        category: 'players',
        control: 'boolean',
        defaultValue: 'true',
        options: yesNo,
        warning: 'Desativar permite contas não verificadas e facilita falsificação de identidade.',
    },
    {
        key: 'enforce-secure-profile',
        label: 'Exigir perfil seguro',
        description: 'Exige chave pública assinada para os jogadores.',
        category: 'players',
        control: 'boolean',
        defaultValue: 'true',
        options: yesNo,
    },
    {
        key: 'white-list',
        label: 'Whitelist',
        description: 'Permite entrada somente de jogadores autorizados.',
        category: 'players',
        control: 'boolean',
        defaultValue: 'false',
        options: yesNo,
    },
    {
        key: 'enforce-whitelist',
        label: 'Aplicar whitelist imediatamente',
        description: 'Remove jogadores não autorizados quando a whitelist for recarregada.',
        category: 'players',
        control: 'boolean',
        defaultValue: 'false',
        options: yesNo,
    },
    {
        key: 'player-idle-timeout',
        label: 'Tempo limite de inatividade',
        description: 'Minutos até expulsar um jogador inativo. Use 0 para desativar.',
        category: 'players',
        control: 'number',
        defaultValue: '0',
        min: 0,
        max: 2147483647,
    },
    {
        key: 'prevent-proxy-connections',
        label: 'Bloquear conexões por proxy',
        description: 'Compara a origem da conexão com os dados da autenticação.',
        category: 'players',
        control: 'boolean',
        defaultValue: 'false',
        options: yesNo,
    },
    {
        key: 'rate-limit',
        label: 'Limite de pacotes',
        description: 'Máximo de pacotes por segundo antes de desconectar. Use 0 para desativar.',
        category: 'performance',
        control: 'number',
        defaultValue: '0',
        min: 0,
        max: 100000,
    },
    {
        key: 'network-compression-threshold',
        label: 'Limite de compressão',
        description: 'Tamanho mínimo do pacote para compressão. -1 desativa e 0 comprime tudo.',
        category: 'performance',
        control: 'number',
        defaultValue: '256',
        min: -1,
        max: 65535,
    },
    {
        key: 'entity-broadcast-range-percentage',
        label: 'Alcance de entidades',
        description: 'Percentual da distância normal em que entidades são enviadas aos clientes.',
        category: 'performance',
        control: 'number',
        defaultValue: '100',
        min: 10,
        max: 1000,
    },
    {
        key: 'max-tick-time',
        label: 'Tempo máximo de tick',
        description: 'Milissegundos antes do watchdog encerrar um servidor travado. -1 desativa.',
        category: 'performance',
        control: 'number',
        defaultValue: '60000',
        min: -1,
        max: 2147483647,
        warning: 'Desativar o watchdog pode deixar o servidor travado indefinidamente.',
    },
    {
        key: 'max-chained-neighbor-updates',
        label: 'Atualizações encadeadas',
        description: 'Limita atualizações vizinhas consecutivas antes de ignorá-las.',
        category: 'performance',
        control: 'number',
        defaultValue: '1000000',
        min: -1,
        max: 2147483647,
    },
    {
        key: 'sync-chunk-writes',
        label: 'Escrita síncrona de chunks',
        description: 'Prioriza segurança dos dados em vez de velocidade de gravação.',
        category: 'performance',
        control: 'boolean',
        defaultValue: 'true',
        options: yesNo,
    },
    {
        key: 'use-native-transport',
        label: 'Transporte nativo',
        description: 'Usa otimizações de rede disponíveis em servidores Linux.',
        category: 'performance',
        control: 'boolean',
        defaultValue: 'true',
        options: yesNo,
    },
    {
        key: 'op-permission-level',
        label: 'Nível de permissão dos operadores',
        description: 'Nível padrão de comandos permitido para operadores.',
        category: 'advanced',
        control: 'select',
        defaultValue: '4',
        options: [
            { label: '1 — Moderador básico', value: '1' },
            { label: '2 — Administração', value: '2' },
            { label: '3 — Gerenciamento', value: '3' },
            { label: '4 — Acesso total', value: '4' },
        ],
    },
    {
        key: 'function-permission-level',
        label: 'Nível das funções',
        description: 'Nível de permissão usado por funções de datapacks.',
        category: 'advanced',
        control: 'select',
        defaultValue: '2',
        options: [
            { label: '1 — Básico', value: '1' },
            { label: '2 — Administração', value: '2' },
            { label: '3 — Gerenciamento', value: '3' },
            { label: '4 — Acesso total', value: '4' },
        ],
    },
    {
        key: 'broadcast-console-to-ops',
        label: 'Console para operadores',
        description: 'Envia a saída dos comandos do console aos operadores online.',
        category: 'advanced',
        control: 'boolean',
        defaultValue: 'true',
        options: yesNo,
    },
    {
        key: 'broadcast-rcon-to-ops',
        label: 'RCON para operadores',
        description: 'Envia a saída dos comandos RCON aos operadores online.',
        category: 'advanced',
        control: 'boolean',
        defaultValue: 'true',
        options: yesNo,
    },
    {
        key: 'enable-query',
        label: 'Habilitar Query',
        description: 'Ativa o protocolo GameSpy4 para consulta externa.',
        category: 'advanced',
        control: 'boolean',
        defaultValue: 'false',
        options: yesNo,
    },
    {
        key: 'enable-rcon',
        label: 'Habilitar RCON',
        description: 'Permite administração remota pela porta RCON.',
        category: 'advanced',
        control: 'boolean',
        defaultValue: 'false',
        options: yesNo,
        warning: 'Configure uma senha forte e uma alocação de porta antes de habilitar.',
    },
    {
        key: 'rcon.password',
        label: 'Senha RCON',
        description: 'Senha usada por clientes RCON. Nunca compartilhe este valor.',
        category: 'advanced',
        control: 'text',
        defaultValue: '',
        placeholder: 'Use uma senha longa e exclusiva',
        warning: 'Este valor é armazenado em texto simples no server.properties.',
    },
];

export const propertyPresets: PropertyPreset[] = [
    {
        id: 'survival',
        name: 'Survival equilibrado',
        description: 'Experiência clássica, segura e pronta para uma comunidade.',
        accent: '#22c55e',
        values: {
            gamemode: 'survival',
            difficulty: 'normal',
            hardcore: 'false',
            pvp: 'true',
            'allow-flight': 'false',
            'force-gamemode': 'false',
            'spawn-protection': '16',
            'online-mode': 'true',
            'view-distance': '10',
            'simulation-distance': '8',
        },
    },
    {
        id: 'private',
        name: 'Servidor privado',
        description: 'Whitelist obrigatória e jogadores ocultos no status.',
        accent: '#8b5cf6',
        values: {
            'online-mode': 'true',
            'white-list': 'true',
            'enforce-whitelist': 'true',
            'hide-online-players': 'true',
            'max-players': '20',
            difficulty: 'normal',
        },
    },
    {
        id: 'creative',
        name: 'Criativo',
        description: 'Construção livre com voo e command blocks habilitados.',
        accent: '#06b6d4',
        values: {
            gamemode: 'creative',
            difficulty: 'peaceful',
            pvp: 'false',
            'allow-flight': 'true',
            'force-gamemode': 'true',
            'enable-command-block': 'true',
            'spawn-protection': '0',
        },
    },
    {
        id: 'hardcore',
        name: 'Hardcore',
        description: 'Dificuldade máxima e apenas uma vida por jogador.',
        accent: '#ef4444',
        values: {
            gamemode: 'survival',
            difficulty: 'hard',
            hardcore: 'true',
            pvp: 'true',
            'online-mode': 'true',
            'force-gamemode': 'true',
        },
    },
    {
        id: 'optimized',
        name: 'Desempenho',
        description: 'Valores conservadores para reduzir o uso de CPU e rede.',
        accent: '#f59e0b',
        values: {
            'view-distance': '8',
            'simulation-distance': '6',
            'entity-broadcast-range-percentage': '75',
            'network-compression-threshold': '256',
            'use-native-transport': 'true',
            'sync-chunk-writes': 'true',
        },
    },
];

export const definitionByKey = propertyDefinitions.reduce<Record<string, PropertyDefinition>>((map, definition) => {
    map[definition.key] = definition;
    return map;
}, {});
